#! /bin/sh

### BEGIN INIT INFO
# Provides:          GM mentions bot
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Runs bot which extends mentions possibilities in GM
# Description: Runs bot which extends mentions possibilities in GM
### END INIT INFO

N=/etc/init.d/gm-mentions

set -e

case "$1" in
  start)
    if [ -f /var/run/gm-mentions.pid ]; then
      echo Already running
    else
      touch /var/run/gm-mentions.pid && /var/lib/gm-mentions -port 55555 >> /var/log/gm-mentions.log&
      echo $! > /var/run/gm-mentions.pid
      echo OK
    fi
    ;;
  stop)
    if [ -f /var/run/gm-mentions.pid ]; then
      kill -9 `cat /var/run/gm-mentions.pid` && rm /var/run/gm-mentions.pid
      echo OK
    else
      echo Not running
    fi
    ;;
  restart)
    service gm-mentions stop
    service gm-mentions start
    ;;
esac

exit 0
